[package]
name = "nes"
version = "0.1.0"
authors = ["Mitchell Cohen <mitch.cohen@me.com>"]
edition = "2018"

[lib]
name="nes"
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"
wasm-bindgen = "0.2.50"
colored = "2.0"